spring:
  data:
    mongodb:
      database: library

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "metrics, loggers, health"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    defaults:
      enabled: true