version: '3'
services:
  mongo:
    image: mongo
    container_name: library
    ports:
      - 27017:27017
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"